# config.py

# ✅ 텔레그램 봇 설정
TELEGRAM_TOKEN = '7213273799:AAEcuDAiureO1jY32JMtELcWsoJjHub5Pv0'
TELEGRAM_CHAT_ID = ['7505401062', '7576776181']
API_URL = f'https://api.telegram.org/bot{TELEGRAM_TOKEN}'

# ✅ 분석 대상 심볼 (MEXC 선물 표기 기준)
SYMBOLS = ['BTCUSDT', 'ETHUSDT', 'ETHFIUSDT', 'SUIUSDT', 'XRPUSDT', 'DOGEUSDT', 'WLDUSDT', 'PEPEUSDT', 'SEIUSDT', 'LINKUSDT', 'APTUSDT', 'FLOKIUSDT', 'ANIUSDT', 'SPKUSDT', 'PUMPUSDT', '1000BONKUSDT']

# 전략 분석 주기 (초)
STRATEGY_INTERVAL_SECONDS = 600

# 스파이크 감지 폴링 주기 (초)
SPIKE_POLL_INTERVAL_SECONDS = 1
